#!/usr/bin/env bash

cfssl gencert -initca csr/ca.csr.json | cfssljson -bare ca
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=csr/config.json -profile=default csr/server.csr.json | cfssljson -bare server

GOSSIP_ENCRYPTION_KEY=$(consul keygen)

# Create namespace consul
kubectl create ns consul

# Create the Consul Secret and Configmap

kubectl create secret -n consul generic consul \
  --from-literal="gossip-encryption-key=${GOSSIP_ENCRYPTION_KEY}" \
  --from-file=tls/ca.pem \
  --from-file=tls/consul-server.pem \
  --from-file=tls/consul-server-key.pem

kubectl create configmap -n consul consul --from-file=configs/consul-server.json

# Create the Consul Headless Service
kubectl create -n consul -f services/consul.yaml

# Create the Consul Service Account
kubectl apply -n consul -f serviceaccounts/consul.yaml
kubectl apply -n consul -f clusterroles/consul.yaml

# Create Persistent Volumes
kubectl apply -n consul -f persistentvolumes/

# Deploy StatefulSet Consul
kubectl create -n consul -f statefulsets/consul.yaml

# Deploy PodDisruptionBudget for Consul
kubectl create -n consul -f poddisruptionbudget/consul.yaml